# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt install python3.7
    python3.7 -m pip install pipenv
  displayName: 'Set up Python on host OS'

- script: python3.7 -m pipenv sync --dev
  displayName: 'Set up pipenv environment'

- script: python3.7 -m pipenv run python -m flake8
  displayName: 'Run lint'
