# Copy this configuration file to config.yml and edit it.

Qud install folder: C:\Program Files (x86)\Steam\steamapps\common\Caves of Qud
Discord bot token: XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXX

decode cog:
  ignore: [502293569764327444]  # Cryptogull
  listen channels: [449342897788026882, 571405896597635073]  #character-builds, #build-club

wiki cog:
  wiki: cavesofqud.gamepedia.com
  search namespaces: [0, 14]  # Main, Category
  fuzzy cutoff: 75  # quality of fuzzy search match to cut off at
  title search limit: 10  # number of pages to return from ?wiki command
  fulltext search limit: 5  # number of pages to return from the ?wikisearch command
  title dump limit: 5000  # how many page titles to download at once (bot limit: 5000)
  title cache time limit: 900  # how many seconds to keep the title cache (900=15min)
